# Generated by Django 4.1.4 on 2022-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='uuidField',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
