# Generated by Django 4.1.4 on 2022-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_confession_uuidfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='uuidField',
            field=models.UUIDField(auto_created=True),
        ),
    ]
