# Generated by Django 4.1.4 on 2022-12-09 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_confession_uuidfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='uuidField',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
