# Generated by Django 4.1.4 on 2022-12-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_confession_uuidfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='uuidField',
        ),
    ]
