# Generated by Django 4.1.4 on 2022-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_remove_confession_uuidfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
