# Generated by Django 4.1.4 on 2022-12-10 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_confession_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='uuidField',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
