# Generated by Django 4.1.4 on 2022-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_confession_uuidfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='mediaFiles'),
        ),
    ]
