# Generated by Django 4.1.4 on 2022-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_confession_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
