# Generated by Django 4.1.4 on 2022-12-14 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
